/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from './encoder';
import { Observable }                                        from 'rxjs';

import { JsonListContainerStronaCmsListaDto } from '../modele/json-list-container-strona-cms-lista-dto';
import { JsonObjectContainerStronaCmsSzczegolyOpenDto } from '../modele/json-object-container-strona-cms-szczegoly-open-dto';
// import { RequestErrorResponse } from '../model/models';

import { BASE_PATH, COLLECTION_FORMATS }                     from './variables';
import { Configuration }                                     from './configuration';



@Injectable({
  providedIn: 'root'
})
export class ControllerStronyCmsOpenService {

    protected basePath = 'https://testmapa.um.warszawa.pl/api/modul-mapowy';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param rodzaj Określa rodzaj zwracanej strony.
     * @param wyszukiwanaFraza Parametr filtrowania jednopolowego.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pobierzListeStronOpen(rodzaj: string, wyszukiwanaFraza: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/json'}): Observable<JsonListContainerStronaCmsListaDto>;
    public pobierzListeStronOpen(rodzaj: string, wyszukiwanaFraza: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/json'}): Observable<HttpResponse<JsonListContainerStronaCmsListaDto>>;
    public pobierzListeStronOpen(rodzaj: string, wyszukiwanaFraza: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/json'}): Observable<HttpEvent<JsonListContainerStronaCmsListaDto>>;
    public pobierzListeStronOpen(rodzaj: string, wyszukiwanaFraza: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*' | 'application/json'}): Observable<any> {
        if (rodzaj === null || rodzaj === undefined) {
            throw new Error('Required parameter rodzaj was null or undefined when calling pobierzListeStronOpen.');
        }
        if (wyszukiwanaFraza === null || wyszukiwanaFraza === undefined) {
            throw new Error('Required parameter wyszukiwanaFraza was null or undefined when calling pobierzListeStronOpen.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (rodzaj !== undefined && rodzaj !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>rodzaj, 'rodzaj');
        }
        if (wyszukiwanaFraza !== undefined && wyszukiwanaFraza !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>wyszukiwanaFraza, 'wyszukiwanaFraza');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                '*/*',
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<JsonListContainerStronaCmsListaDto>(`${this.configuration.basePath}/open/cms`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param sciezkaUrl
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pobierzStronePoSciezce(sciezkaUrl: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/json'}): Observable<JsonObjectContainerStronaCmsSzczegolyOpenDto>;
    public pobierzStronePoSciezce(sciezkaUrl: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/json'}): Observable<HttpResponse<JsonObjectContainerStronaCmsSzczegolyOpenDto>>;
    public pobierzStronePoSciezce(sciezkaUrl: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*' | 'application/json'}): Observable<HttpEvent<JsonObjectContainerStronaCmsSzczegolyOpenDto>>;
    public pobierzStronePoSciezce(sciezkaUrl: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*' | 'application/json'}): Observable<any> {
        if (sciezkaUrl === null || sciezkaUrl === undefined) {
            throw new Error('Required parameter sciezkaUrl was null or undefined when calling pobierzStronePoSciezce.');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                '*/*',
                'application/json'
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<JsonObjectContainerStronaCmsSzczegolyOpenDto>(`${this.configuration.basePath}/open/cms/${encodeURIComponent(String(sciezkaUrl))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
