/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AktualnosciListaDto { 
    uuid?: string;
    tytul?: string;
    tytulEn?: string;
    tresc?: string;
    trescEn?: string;
    trescProsta?: string;
    trescEnProsta?: string;
    dataUtworzenia?: string;
    archiwum?: boolean;
    czyWlasciciel?: boolean;
}

