/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JezykStronyObiektDto { 
    obiektEnum?: JezykStronyObiektDto.ObiektEnumEnum;
    tlumaczenie?: string;
}
export namespace JezykStronyObiektDto {
    export type ObiektEnumEnum = 'PL' | 'EN';
    export const ObiektEnumEnum = {
        Pl: 'PL' as ObiektEnumEnum,
        En: 'EN' as ObiektEnumEnum
    };
}


