/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KategoriaGrupaMapOpenDto } from './kategoria-grupa-map-open-dto';
import { TypKategoriiMapObiektDto } from './typ-kategorii-map-obiekt-dto';


export interface KategoriaMapOpenDto {
    uuid?: string;
    nazwa?: string;
    // nazwaEn?: string;
    numerWTabeli?: number;
    typ?: TypKategoriiMapObiektDto;
    rodzaj?: string;
    grupyMap?: Array<KategoriaGrupaMapOpenDto>;
}

