/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypKomuniaktuObiektDto } from './typ-komuniaktu-obiekt-dto';


export interface KomunikatSzczegolyDto { 
    uuid?: string;
    id?: number;
    tresc: string;
    trescProsta?: string;
    trescEn: string;
    trescEnProsta?: string;
    typ: TypKomuniaktuObiektDto;
    terminOd?: string;
    terminDo?: string;
    cyklicznosc?: boolean;
    interwal?: number;
    czasWyswietlania?: number;
    czyWlasciciel?: boolean;
}

