/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypMapyObiektDto } from './typ-mapy-obiekt-dto';
import { WidokMapyMapaSzczegolyDto } from './widok-mapy-mapa-szczegoly-dto';


export interface MapaSzczegolyDto {
    uuid?: string;
    nazwa: string;
    nazwaEn: string;
    typ: TypMapyObiektDto;
    opisKafelka: string;
    opisKafelkaEn: string;
    opisMapyWPortaluMapowym?: string;
    opisMapyWPortaluMapowymEn?: string;
    adresUrl?: string;
    tagi?: string;
    tagiEn?: string;
    status: MapaSzczegolyDto.StatusEnum;
    wersja: MapaSzczegolyDto.WersjaEnum;
    domyslnaSkala?: string;
    domyslnaWspolrzednaSrodkaX?: number;
    domyslnaWspolrzednaSrodkaY?: number;
    domyslnaSkalaPoWyszukaniuPunktu?: string;
    sciezkaDoPlikuZGrafika: string;
    czyWlasciciel?: boolean;
    definicjaMapy?: WidokMapyMapaSzczegolyDto;
}
export namespace MapaSzczegolyDto {
    export type StatusEnum = 'ROBOCZA' | 'UKRYTA' | 'OPUBLIKOWANA' | 'PRYWATNA';
    export const StatusEnum = {
        Robocza: 'ROBOCZA' as StatusEnum,
        Ukryta: 'UKRYTA' as StatusEnum,
        Opublikowana: 'OPUBLIKOWANA' as StatusEnum,
        Prywatna: 'PRYWATNA' as StatusEnum
    };
    export type WersjaEnum = 'DESKTOPOWA' | 'MOBILNA' | 'OBIE';
    export const WersjaEnum = {
        Desktopowa: 'DESKTOPOWA' as WersjaEnum,
        Mobilna: 'MOBILNA' as WersjaEnum,
        Obie: 'OBIE' as WersjaEnum
    };
}


