/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JezykStronyObiektDto } from './jezyk-strony-obiekt-dto';


export interface StronaCmsTlumaczenieDto { 
    uuid?: string;
    nazwa: string;
    tagi?: string;
    tresc?: string;
    trescProsta?: string;
    jezykStronyObiektDto: JezykStronyObiektDto;
}

