/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TypMapyObiektDto { 
    obiektEnum?: TypMapyObiektDto.ObiektEnumEnum;
    tlumaczenie?: string;
}
export namespace TypMapyObiektDto {
    export type ObiektEnumEnum = 'MAPA' | 'SERWIS_ZEWNETRZNY';
    export const ObiektEnumEnum = {
        Mapa: 'MAPA' as ObiektEnumEnum,
        SerwisZewnetrzny: 'SERWIS_ZEWNETRZNY' as ObiektEnumEnum
    };
}


