/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TypGrupyKonfiguracjiObiektDto { 
    obiektEnum?: TypGrupyKonfiguracjiObiektDto.ObiektEnumEnum;
    tlumaczenie?: string;
}
export namespace TypGrupyKonfiguracjiObiektDto {
    export type ObiektEnumEnum = 'AKTUALNOSCI' | 'UKLADY_WSPOLRZEDNYCH' | 'FORMATY_POBIERANIA' | 'MAPY_DOMYSLNE' | 'INNE_USTAWIENIA' | 'UW_ANALIZY_PRZESTRZENNE' | 'UW_WYNIKI_SELEKCJI' | 'UW_WYNIKI_POMIARU' | 'UW_WYDRUK_MAPY' | 'UW_POBIERANIE_WARSTWY_KATALOGU' | 'FP_ANALIZY_PRZESTRZENNE' | 'FP_WYNIKI_SELEKCJI' | 'FP_WYNIKI_POMIARU' | 'FP_WYDRUK_MAPY' | 'FP_POBIERANIE_WARSTWY_KATALOGU' | 'DOMYSLNA_DLA_ULIC_I_ADRESOW' | 'DOMYSLNA_DLA_OBIEKTOW' | 'DOMYSLNA_DLA_BLEDNEGO_LINKU' | 'LIMIT_WIDOCZNYCH_WYNIKOW_WYSZUKIWANIA' | 'LIMIT_WARSTW_MAPY' | 'PRZECHOWYWANIE_MAP';
    export const ObiektEnumEnum = {
        Aktualnosci: 'AKTUALNOSCI' as ObiektEnumEnum,
        UkladyWspolrzednych: 'UKLADY_WSPOLRZEDNYCH' as ObiektEnumEnum,
        FormatyPobierania: 'FORMATY_POBIERANIA' as ObiektEnumEnum,
        MapyDomyslne: 'MAPY_DOMYSLNE' as ObiektEnumEnum,
        InneUstawienia: 'INNE_USTAWIENIA' as ObiektEnumEnum,
        UwAnalizyPrzestrzenne: 'UW_ANALIZY_PRZESTRZENNE' as ObiektEnumEnum,
        UwWynikiSelekcji: 'UW_WYNIKI_SELEKCJI' as ObiektEnumEnum,
        UwWynikiPomiaru: 'UW_WYNIKI_POMIARU' as ObiektEnumEnum,
        UwWydrukMapy: 'UW_WYDRUK_MAPY' as ObiektEnumEnum,
        UwPobieranieWarstwyKatalogu: 'UW_POBIERANIE_WARSTWY_KATALOGU' as ObiektEnumEnum,
        FpAnalizyPrzestrzenne: 'FP_ANALIZY_PRZESTRZENNE' as ObiektEnumEnum,
        FpWynikiSelekcji: 'FP_WYNIKI_SELEKCJI' as ObiektEnumEnum,
        FpWynikiPomiaru: 'FP_WYNIKI_POMIARU' as ObiektEnumEnum,
        FpWydrukMapy: 'FP_WYDRUK_MAPY' as ObiektEnumEnum,
        FpPobieranieWarstwyKatalogu: 'FP_POBIERANIE_WARSTWY_KATALOGU' as ObiektEnumEnum,
        DomyslnaDlaUlicIAdresow: 'DOMYSLNA_DLA_ULIC_I_ADRESOW' as ObiektEnumEnum,
        DomyslnaDlaObiektow: 'DOMYSLNA_DLA_OBIEKTOW' as ObiektEnumEnum,
        DomyslnaDlaBlednegoLinku: 'DOMYSLNA_DLA_BLEDNEGO_LINKU' as ObiektEnumEnum,
        LimitWidocznychWynikowWyszukiwania: 'LIMIT_WIDOCZNYCH_WYNIKOW_WYSZUKIWANIA' as ObiektEnumEnum,
        LimitWarstwMapy: 'LIMIT_WARSTW_MAPY' as ObiektEnumEnum,
        PrzechowywanieMap: 'PRZECHOWYWANIE_MAP' as ObiektEnumEnum
    };
}


