/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TypKategoriiMapObiektDto { 
    obiektEnum?: TypKategoriiMapObiektDto.ObiektEnumEnum;
    tlumaczenie?: string;
}
export namespace TypKategoriiMapObiektDto {
    export type ObiektEnumEnum = 'KATEGORIA_TEMATYCZNA' | 'WYROZNIONE_MAPY';
    export const ObiektEnumEnum = {
        KategoriaTematyczna: 'KATEGORIA_TEMATYCZNA' as ObiektEnumEnum,
        WyroznioneMapy: 'WYROZNIONE_MAPY' as ObiektEnumEnum
    };
}


