/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WidokMapyJezykDto } from './widok-mapy-jezyk-dto';
import { WidokMapyFunkcjeDodatkoweDto } from './widok-mapy-funkcje-dodatkowe-dto';
import { WidokMapyOknoInformacyjneWarstwyDto } from './widok-mapy-okno-informacyjne-warstwy-dto';
import { WidokMapyOpcjeKlastrowaniaDto } from './widok-mapy-opcje-klastrowania-dto';


export interface WidokMapyWarstwaSzczegolyDto {
    zrodloMVC: string;
    nazwaMVC: string;
    alias?: WidokMapyJezykDto;
    typ: string;
    minSkalaWidocznosci: number;
    maksSkalaWidocznosci: number;
    minSkalaKlikalnosci: number;
    maksParametrKlastrowania: number;
    widocznoscEtykiet?: boolean;
    przezroczystosc: number;
    pobieranieDanych?: boolean;
    opisZrodlaDanych?: WidokMapyJezykDto;
    znakWodny?: boolean;
    analizaPrzestrzenna?: boolean;
    informacjeOObiekcie?: boolean;
    multimedia?: boolean;
    zalaczniki?: boolean;
    funkcjeDodatkowe?: Array<WidokMapyFunkcjeDodatkoweDto>;
    warstwyKonfliktowe?: Array<string>;
    informacjeOWarstwie?: WidokMapyOknoInformacyjneWarstwyDto;
    opcjeKlastrowania?: WidokMapyOpcjeKlastrowaniaDto;
    dynamicTileLayer?: boolean;
    antyaliasing?: boolean;
}

