/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WidokMapyJezykDto } from './widok-mapy-jezyk-dto';
import { WidokMapyWarstwaDto } from './widok-mapy-warstwa-dto';


export interface WidokMapyMapaPodkladowaDto { 
    nazwa?: WidokMapyJezykDto;
    sciezkaDoPlikuGrafiki?: string;
    warstwa?: WidokMapyWarstwaDto;
}

