/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WidokMapyJezykDto } from './widok-mapy-jezyk-dto';
import { WidokMapyParametrySterujaceWarstwy } from './widok-mapy-parametry-sterujace-warstwy';
import { WidokMapyWarstwaSzczegolyDto } from './widok-mapy-warstwa-szczegoly-dto';


export interface WidokMapyWarstwaDto { 
    uuid: string;
    uuidMapa: string;
    typWyswietlania: string;
    typGeometrii?: string;
    nazwaOficjalna?: WidokMapyJezykDto;
    opisDodatkowy?: WidokMapyJezykDto;
    tagi?: string;
    tagiEn?: string;
    sciezkaDoPlikuSymbolu?: string;
    rozwiniecieWLegendzie?: boolean;
    widocznoscWLegendzie?: boolean;
    mozliwoscZmianyWidocznosci?: boolean;
    mozliwoscRozwinieciaWlegendzie?: boolean;
    wieleWarstw?: boolean;
    szczegolyWarstwy?: WidokMapyWarstwaSzczegolyDto;
    parametrySterujace?: WidokMapyParametrySterujaceWarstwy;
    usunieta?: boolean;
}

